language: android

sudo: false

jdk: openjdk7

env:
        matrix:
                - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a

android:
        components:
                - build-tools-23.0.2
                - android-23
                - extra

script:
        - gradle build

after-success:
        - echo "Travis branch is $TRAVIS_BRANCH"
        - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"

notifications:
        email: false
