language: android

sudo: false

jdk:
        - openjdk7

android:
        components:
                - build-tools-22.0.0
                - android-22
                - extra
script:
        - echo "Travis branch is $TRAVIS_BRANCH"
